---
title: "Exercise 1"
author: "Adam Sulak, Onder Akacik, Arda Ergin"
date: "2024-02-22"
output:
  pdf_document: default
  html_document: default
---

```{r}
options(digits=3)

library(dplyr)
library(ggplot2)
library(car)
library(corrplot)
library(glmnet)
color_choice <- "Dark2"
```

# Exercise 2

```{r}
data <- read.csv("Birthweight.csv")
```

## Question 2a)

```{r}
model <- lm(
    Birthweight ~ Length + Headcirc + Gestation + mage + mnocig + mheight + mppwt + fage + fedyrs + fnocig + fheight,
    data = data
)
#model <- lm(Birthweight ~ ., data = data)
summary(model)
```

```{r}
# par(mfrow=c(2,2))
plot(model)

# 
resid_ordered <- order(abs(residuals(model)))
u = rep(0,length(resid_ordered))
u[length(resid_ordered)] = 1
# 
cooks.distance(model)
plot(cooks.distance(model), type="b")

#forbeslm_42 = lm(y~x+u11); summary(forbeslm11)
```

Collinearity:

```{r}
car::vif(model)
```

no variables have a VIF value that is higher than 5

```{r}
# Calculate correlation matrix
cor_matrix <- cor(data[, -c(1,3)]) # Exclude response variable Birthweight

# Plot the correlation matrix
corrplot(cor_matrix, 
         method = "circle", type = "upper", tl.col = "black", tl.cex = 0.6)
```

## Question 2b)

```{r}
step_down_model <- step(model, direction = 'backward')
summary(step_down_model)
par(mfrow = c(1,2))
plot(step_down_model)
```

## Question 2c)

```{r}
step_down_model <- lm(Birthweight ~ Gestation + Headcirc, data = data)

head_mean <- mean(data$Gestation)
gest_mean <- mean(data$Headcirc)

df <- data.frame(Gestation = gest_mean, Headcirc = head_mean)

ci <- predict(step_down_model, newdata = df, interval = 'confidence')
pi <- predict(step_down_model, newdata = df, interval = 'prediction')


ci; pi
```

## Question 2d)

LASSO method

```{r}
x <- subset(data, select = -Birthweight)
y <- data$Birthweight

train=sample(1:nrow(x),0.67*nrow(x))
x_train=x[train,]; y_train=y[train]
x_test=x[-train,]; y_test = y[-train]

y_predict_lm=predict(step_down_model,newdata=data[-train,]) # predict for the test rows
mse_lm=mean((y_test-y_predict_lm)^2)# prediction quality by the linear model

lasso_model <- glmnet(x_train, y_train, alpha = 1)


lasso_cv <- cv.glmnet(
    as.matrix(x_train),
    y_train,
    alpha = 1,
    type.measure="mse",
    nfolds=5
)

lasso_pred1=predict(lasso_model,s=lasso_cv$lambda.min,newx=as.matrix(x_test))
lasso_pred2=predict(lasso_model,s=lasso_cv$lambda.1se,newx=as.matrix(x_test))
mse1_lasso=mean((y_test-lasso_pred1)^2)
mse2_lasso=mean((y_test-lasso_pred2)^2)


plot(lasso_model, xvar="lambda", label = TRUE)
plot(lasso_model, xvar="dev", label = TRUE)
plot(lasso_cv)
coef(lasso_cv, s= lasso_cv$lambda.1se)
# coef(lasso_cv_model, s= lasso_cv_model$lambda.min)

mse_lm; mse1_lasso; mse2_lasso
```

## Question 2e)

```{r}
smoke_model_all <- lm( lowbwt ~ Gestation+smoker+mage35, data=data)
# summary(smoke_model_all)

# manual step down
m1 <- lm(lowbwt ~ Gestation+smoker, data=data)
m2 <- lm(lowbwt ~ Gestation, data=data)
# summary(m1); summary(m2)

# automatic step down
smoke_step_down <- step(smoke_model_all, direction = 'backward')
summary(smoke_step_down)
plot(smoke_step_down)
```

Using drop down methods we conclude age has no significance. We select Gestation and smoker parameters. \## Question 2f)

## Question 2g)

## Question 2h)

## Question 2i)
